-- Migration 0050 — QA fixes from full-site quality audit.
--
-- Three classes of fix:
--
-- 1. Idempotency-breaking gaps surfaced by the QA pass:
--      • production_formats had NO unique constraint at all, so the
--        ON CONFLICT DO NOTHING in every seed was a no-op (the PK is
--        bigserial; conflict never fires). Re-running any seed silently
--        duplicated format rows.
--      • production_locations had NO unique on (production_id, name),
--        forcing every seed to implement a two-roundtrip
--        SELECT-EXISTS-THEN-UPDATE-OR-INSERT workaround.
--      • production_awards UNIQUE included the nullable
--        recipient_person_id column. Postgres treats NULLs as DISTINCT
--        in UNIQUE constraints, so production-level awards (Best Picture,
--        Best VFX team awards, etc. — every recipient_person_id IS NULL)
--        bypassed the conflict target and duplicated on every re-run.
--
--    All three are repaired with NULLS NOT DISTINCT (Postgres 15+).
--    Pre-existing duplicates are deduped via the DELETE-by-ctid pattern
--    before the constraint is added.
--
-- 2. Missing FK indexes — ten reverse-lookup paths lacked indexes
--    Postgres does NOT create automatically on foreign keys. Cheap to
--    add now, opens future query options.
--
-- 3. Trigram GIN indexes on three columns that admin search hits with
--    unanchored ILIKE '%…%' patterns:
--      • production_formats.acquisition_format
--      • media_assets.title
--      • media_assets.url
--    Will degrade with corpus growth without these.
--
-- drizzle-kit already wraps each migration in its own transaction, so
-- this file is NOT explicitly BEGIN/COMMIT-wrapped.

-- ─────────────────────────────────────────────────────────────────────
-- 1a. production_formats — dedupe + natural-key unique
-- ─────────────────────────────────────────────────────────────────────

DELETE FROM production_formats a
USING production_formats b
WHERE a.ctid < b.ctid
  AND a.production_id     = b.production_id
  AND a.aspect_ratio      = b.aspect_ratio
  AND a.acquisition_format = b.acquisition_format;

-- DROP+ADD pattern is idempotent: drizzle-kit's apply transaction is the
-- atomicity scope. The DROP IF EXISTS lets the migration be re-run if it
-- partially applied during development.
ALTER TABLE production_formats
  DROP CONSTRAINT IF EXISTS production_formats_natural_key;
ALTER TABLE production_formats
  ADD CONSTRAINT production_formats_natural_key
  UNIQUE NULLS NOT DISTINCT (production_id, aspect_ratio, acquisition_format);

-- ─────────────────────────────────────────────────────────────────────
-- 1b. production_locations — dedupe + natural-key unique
-- ─────────────────────────────────────────────────────────────────────

DELETE FROM production_locations a
USING production_locations b
WHERE a.ctid < b.ctid
  AND a.production_id = b.production_id
  AND a.name          = b.name;

ALTER TABLE production_locations
  DROP CONSTRAINT IF EXISTS production_locations_natural_key;
ALTER TABLE production_locations
  ADD CONSTRAINT production_locations_natural_key
  UNIQUE (production_id, name);

-- ─────────────────────────────────────────────────────────────────────
-- 1c. production_awards — replace existing unique with NULLS NOT DISTINCT
-- ─────────────────────────────────────────────────────────────────────

-- Dedupe pre-existing production-level award rows that slipped through
-- the NULL-distinct hole. Keep the row with the largest id (most recent).
DELETE FROM production_awards a
USING production_awards b
WHERE a.id < b.id
  AND a.production_id IS NOT DISTINCT FROM b.production_id
  AND a.award_org     IS NOT DISTINCT FROM b.award_org
  AND a.category      IS NOT DISTINCT FROM b.category
  AND a.year          IS NOT DISTINCT FROM b.year
  AND a.recipient_person_id IS NOT DISTINCT FROM b.recipient_person_id;

-- The original UNIQUE constraint name was auto-generated by drizzle as
-- production_awards_production_id_award_org_category_year_rec_key
-- (not production_awards_unique). Drop whichever exists, then re-add.
ALTER TABLE production_awards
  DROP CONSTRAINT IF EXISTS production_awards_unique,
  DROP CONSTRAINT IF EXISTS production_awards_production_id_award_org_category_year_rec_key;

ALTER TABLE production_awards
  ADD CONSTRAINT production_awards_unique
  UNIQUE NULLS NOT DISTINCT (production_id, award_org, category, year, recipient_person_id);

-- ─────────────────────────────────────────────────────────────────────
-- 2. Missing FK indexes (reverse-lookup paths)
-- ─────────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS studios_parent_studio_idx
  ON studios (parent_studio_id) WHERE parent_studio_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS vfx_house_highlights_production_idx
  ON vfx_house_highlights (production_id);

CREATE INDEX IF NOT EXISTS production_vfx_techniques_technique_idx
  ON production_vfx_techniques (technique_id);

CREATE INDEX IF NOT EXISTS production_video_timestamp_annotations_evidence_idx
  ON production_video_timestamp_annotations (evidence_item_id)
  WHERE evidence_item_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS production_keyframes_scene_idx
  ON production_keyframes (scene_id) WHERE scene_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS lighting_setup_fixtures_equipment_usage_idx
  ON lighting_setup_fixtures (equipment_usage_id);

CREATE INDEX IF NOT EXISTS stunt_sequences_scene_idx
  ON stunt_sequences (scene_id) WHERE scene_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS stunt_sequences_vfx_handoff_house_idx
  ON stunt_sequences (vfx_handoff_house_id) WHERE vfx_handoff_house_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS stunt_sequences_safety_officer_person_idx
  ON stunt_sequences (safety_officer_person_id) WHERE safety_officer_person_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS stunt_sequence_credits_doubling_for_person_idx
  ON stunt_sequence_credits (doubling_for_person_id) WHERE doubling_for_person_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS stunt_doubling_credits_primary_sequence_idx
  ON stunt_doubling_credits (primary_sequence_id) WHERE primary_sequence_id IS NOT NULL;

-- ─────────────────────────────────────────────────────────────────────
-- 3. Trigram GIN indexes for admin ILIKE search
-- ─────────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS production_formats_acquisition_trgm_idx
  ON production_formats USING gin (acquisition_format gin_trgm_ops);

CREATE INDEX IF NOT EXISTS media_assets_title_trgm_idx
  ON media_assets USING gin (title gin_trgm_ops);

CREATE INDEX IF NOT EXISTS media_assets_url_trgm_idx
  ON media_assets USING gin (url gin_trgm_ops);
